import type { Metadata } from "next";
import { Container, Stack, Box, Typography } from "@mui/material";
import NavBar from "@/containers/NevBar/NevBar";
import { COLORS } from "@/constants";
import LogoutButton from "@/components/logoutButton/LogoutButton";

export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Container maxWidth={false}>
      <Stack overflow={"auto"} height={"100vh"}>
        <Stack position={"fixed"} width={"100vw"} top={0} zIndex={999}>
          <NavBar>
            <LogoutButton/>
          </NavBar>
        </Stack>
        <Stack paddingTop={"70px"}>{children}</Stack>
      </Stack>
    </Container>
  );
}
