import type { Metadata } from "next";
import { Container, Stack, Box, Typography } from "@mui/material";
import NavBar from "@/containers/NevBar/NevBar";
import { COLORS } from "@/constants";

export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
		<Container maxWidth={false}>
			<Stack>
				<NavBar />
				{children}
			</Stack>
		</Container>
	);
}
